use codeup_test_db;



DROP TABLE if exists users;

create table users (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100) NOT NULL,
    password VARCHAR(50) NOT NULL
);

insert into users (username, password) values ('qallkins0@harvard.edu', 'bgsLjOW6');
insert into users (username, password) values ('bdewi1@gov.uk', 'hEky0LA98O');
insert into users (username, password) values ('hstiller2@1688.com', 's38IWwJrV0Z');
insert into users (username, password) values ('afulloway3@simplemachines.org', 'aSt7nDtrXYB');
insert into users (username, password) values ('bwhiteford4@deviantart.com', 'PkyFjRIhGu');
insert into users (username, password) values ('cgare5@nature.com', 'JrHZH89');
insert into users (username, password) values ('mcomazzo6@virginia.edu', 'pHdJkf1XW');
insert into users (username, password) values ('dsmethurst7@typepad.com', 'bcusWoGGNe');
insert into users (username, password) values ('ssurmeyers8@state.gov', 'lPSNkN');
insert into users (username, password) values ('pgreenrod9@tripadvisor.com', 'pDrsxJMb7');
insert into users (username, password) values ('ldannatta@multiply.com', 'ja73Ys53P');
insert into users (username, password) values ('jjoburnb@bloglovin.com', 'YjjXI5xENRA');
insert into users (username, password) values ('mlaughtissec@youtu.be', 'KOssDV98uf');
insert into users (username, password) values ('sprisleyd@slashdot.org', 'r3NQ77');
insert into users (username, password) values ('jmalloye@eepurl.com', 'nkU6JLC2');
insert into users (username, password) values ('mmogief@phpbb.com', 'B1FhQFfxg5j');
insert into users (username, password) values ('ssangerg@sfgate.com', 'AYMU2cuQ');
insert into users (username, password) values ('ascoylesh@digg.com', 'HihFtbU');
insert into users (username, password) values ('ddittsi@shop-pro.jp', 'YnfVJT');
insert into users (username, password) values ('hgockelerj@yandex.ru', 'AnscjeAJIoTu');
insert into users (username, password) values ('lbelink@npr.org', 'vtorC0kqFDjY');
insert into users (username, password) values ('aciepluchl@wordpress.org', 'fpumBCV');
insert into users (username, password) values ('bsabatim@census.gov', 'NZ5sR8vB9iyv');
insert into users (username, password) values ('sleflemingn@squarespace.com', 'qKW0tKF7d');
insert into users (username, password) values ('ypickardo@scientificamerican.com', 'aYfNov');
insert into users (username, password) values ('erubinowitzp@bizjournals.com', 'yH57l1kd40lz');
insert into users (username, password) values ('mfrancesq@oakley.com', 'groMUbLJ');
insert into users (username, password) values ('fbillinghamr@microsoft.com', '9WR3h36vI');
insert into users (username, password) values ('grillstones@msn.com', 'ofj1BBJeshWu');
insert into users (username, password) values ('tstammirst@cbsnews.com', 'CvK5G4');
insert into users (username, password) values ('mdenfordu@google.pl', 'E2psCAp7Sw');
insert into users (username, password) values ('spelzv@state.gov', 'yVMNImrMvl9');
insert into users (username, password) values ('vpfeufferw@usda.gov', 'MCyyC6');
insert into users (username, password) values ('kblackleechx@wordpress.org', 'kBYYe85');
insert into users (username, password) values ('hmurrocky@soundcloud.com', 'ZVsHyv');
insert into users (username, password) values ('eshelbornez@spotify.com', 'ymR9FvTExlIT');
insert into users (username, password) values ('cherries10@surveymonkey.com', 'FQApbmdKYcHa');
insert into users (username, password) values ('agrout11@cdbaby.com', '1hG6xjn');
insert into users (username, password) values ('cferns12@nhs.uk', '7HBhSVdfwK');
insert into users (username, password) values ('tmadison13@etsy.com', 'h3eqxy7GtvLt');
insert into users (username, password) values ('dlauret14@latimes.com', 'j0lKHHthm');
insert into users (username, password) values ('halcott15@symantec.com', 'IkfLzZPlhk');
insert into users (username, password) values ('gtruesdale16@amazonaws.com', 'sjR05c');
insert into users (username, password) values ('lwear17@hatena.ne.jp', 'uGMIUzCTy7');
insert into users (username, password) values ('bropartz18@apple.com', 'J7yRoB9');
insert into users (username, password) values ('bkersley19@ehow.com', 'smyuZd9j5qU');
insert into users (username, password) values ('eivanshintsev1a@tmall.com', 'cifHegrozk');
insert into users (username, password) values ('vpinwill1b@diigo.com', 'fv9HMeQEbq');
insert into users (username, password) values ('gshah1c@marketwatch.com', '9xYFzOKPEpVH');
insert into users (username, password) values ('aeland1d@yale.edu', 'EbtrSG72J');
insert into users (username, password) values ('lmartyntsev1e@ameblo.jp', 'wyd6mjjIGUmb');
insert into users (username, password) values ('ehrynczyk1f@phoca.cz', '3e87OqHdCwg');
insert into users (username, password) values ('avanleeuwen1g@devhub.com', 'Zi5GXO1eWD');
insert into users (username, password) values ('mmucci1h@creativecommons.org', 'XMBeHjUg9I');
insert into users (username, password) values ('bmcveighty1i@bing.com', 'Uyr9pw');
insert into users (username, password) values ('apercival1j@dion.ne.jp', 'uE2le1c5');
insert into users (username, password) values ('hhaslen1k@multiply.com', 'DS3by2v3');
insert into users (username, password) values ('obrandino1l@nydailynews.com', 'AEkQAvO');
insert into users (username, password) values ('ebrough1m@marketwatch.com', 'DAgkOLQGe');
insert into users (username, password) values ('rsiflet1n@npr.org', '4kXxhW');
insert into users (username, password) values ('jgregori1o@thetimes.co.uk', 'UwbRbKgs');
insert into users (username, password) values ('hmartinet1p@zdnet.com', 'o8P71I');
insert into users (username, password) values ('bgeelan1q@columbia.edu', 'FUJTlY');
insert into users (username, password) values ('cheaker1r@vk.com', 'RNU0IqykMqv');
insert into users (username, password) values ('lgarces1s@google.fr', 'MyncDi5ig3');
insert into users (username, password) values ('mmatschuk1t@cbc.ca', 'jpbzbft');
insert into users (username, password) values ('lolivey1u@de.vu', 'llzUvf2e');
insert into users (username, password) values ('jmatveiko1v@acquirethisname.com', 'A4qQSA');
insert into users (username, password) values ('kfrancesc1w@sakura.ne.jp', 'Wcr4jD');
insert into users (username, password) values ('kbehagg1x@census.gov', 'RpvgBS');
insert into users (username, password) values ('eroskilly1y@diigo.com', '04OwAIR9vu1');
insert into users (username, password) values ('kcanada1z@alexa.com', 'qVfsEzq0ZQ');
insert into users (username, password) values ('bleagas20@cnbc.com', 'N4JLy9i');
insert into users (username, password) values ('nallcott21@ow.ly', 'oaCQ4D8hbe4');
insert into users (username, password) values ('rpinckstone22@hp.com', 'hHxisTu');
insert into users (username, password) values ('vnajara23@dyndns.org', 'aF163y');
insert into users (username, password) values ('nmaiden24@theatlantic.com', 'jxvtX6Z');
insert into users (username, password) values ('kvandenbroek25@shinystat.com', 'YcV8vBe4');
insert into users (username, password) values ('kbeatey26@biglobe.ne.jp', 'gPd7hS7y');
insert into users (username, password) values ('rcalifornia27@wsj.com', '2dx6SO');
insert into users (username, password) values ('bglabach28@yandex.ru', '8HJwRR3DdH');
insert into users (username, password) values ('vkilalea29@army.mil', 'LTzEjqZ');
insert into users (username, password) values ('bsollon2a@netscape.com', 'wzAgPtGwektf');
insert into users (username, password) values ('edobbing2b@sbwire.com', '84QIQledcyd');
insert into users (username, password) values ('rivanyushin2c@skyrock.com', 'wnpjD4fJ1');
insert into users (username, password) values ('abeattie2d@joomla.org', 'Vh98Gh8');
insert into users (username, password) values ('cscholer2e@google.it', 'PRIcPJc0V');
insert into users (username, password) values ('aiston2f@fda.gov', 'mhS9oCd');
insert into users (username, password) values ('llouder2g@mac.com', 'jRAZCG94');
insert into users (username, password) values ('kstorry2h@house.gov', 'f7ElRIVcl');
insert into users (username, password) values ('mhartas2i@auda.org.au', '2uiPxGR');
insert into users (username, password) values ('hdominici2j@blog.com', 'Gw6ivFPsEQ7T');
insert into users (username, password) values ('balker2k@linkedin.com', 'i7pxdDGZb');
insert into users (username, password) values ('alowey2l@multiply.com', '2f0dT0kzz');
insert into users (username, password) values ('felleyne2m@canalblog.com', 'sGNe0K979NgU');
insert into users (username, password) values ('gthripp2n@booking.com', 'qbYvOO');
insert into users (username, password) values ('mciccotti2o@lycos.com', 'FCkWOUqKqJUP');
insert into users (username, password) values ('gitzkovwich2p@tripod.com', '9GLkrHp');
insert into users (username, password) values ('aparren2q@alibaba.com', '3OUVLimhPKye');
insert into users (username, password) values ('edanilin2r@ihg.com', 'L7GshUHyp');
